### ISSUE TITLE
Activating and using the new Multiple Analog Sensors Interfaces implemented in YARP

### ISSUE THREAD

**Issue by nunoguedelha** [robotology-playground/sensors-calib-inertial#18]
This epic is meant for tracking the changes that were required for wrapping the Multiple Analog Sensors Interfaces in scripting languages like Matlab or Python. These interfaces allow to access the MTB accelerometers, gyroscopes and the strain2 IMUs metadata and measurements:

#### History on the Implementation (non exhaustive)
- initial discussions lead by @traversaro for defining the interface: https://github.com/robotology/yarp/issues/1526
- initial implementation on YARP: https://github.com/robotology/yarp/pull/1586, https://github.com/robotology/yarp/pull/1676
- robot configuration: new devices and wrappers configurations were created for supporting the strain2 IMUs
- issue fix in Yarp on `MultipleAnalogSensorsRemapper` class: https://github.com/robotology/yarp/pull/1785

#### Extending to MTB inertial sensors
- [x] extention (@valegagge ) for supporting the new interfaces in `embObjInertials` device (`icub-main/firmware-shared`), which is used for connecting to MTB board inertials sensors: https://github.com/robotology/icub-firmware-shared/issues/24
- [x] respective extension of the robot configuration files on iCubGenova04: https://github.com/robotology/robots-configuration/pull/69
- [x] respective extension of the robot configuration files on iCubGenova02: https://github.com/robotology/robots-configuration/pull/71.

#### Bindings
- [x] Added new interfaces bindings definition (`yarp.i`) in **YARP**: https://github.com/robotology/yarp/pull/1756
- [ ] Added bindings for using `AttachAll` and `DetachAll` methods from `MultipleAnalogSensorsRemapper` class (this is usefull for creating a remapper from a Matlab script using the bindings): PR to be done. Tests ongoing
- [ ] generate respective bindings in `yarp-matlab-bindings`: TBD after tests completed on the Matlab `MultipleAnalogSensorsRemapper` wrapper class.

#### Testing
- [ ] implement the new interfaces in `GazeboYARPPlugins` for testing them on a Gazebo iCub model: Ongoing
