### ISSUE TITLE
Testing low level joint torque control parameters estimation

### ISSUE THREAD

**Issue by nunoguedelha** [robotology-playground/sensors-calib-inertial#9]
### Unit tests
Unit tests are implemented in the scripts package https://github.com/robotology-playground/sensors-calib-inertial/tree/master/src/%2BUT. Just run the scripts `LowlevTauCtrlCalibrator_Proc.m` or `LowlevTauCtrlCalibrator_SM.m` from the working directory https://github.com/robotology-playground/sensors-calib-inertial/tree/master/src/app:
- `LowlevTauCtrlCalibrator_SM.m` --> for testing the state machine transitions only (processing of the user prompts when navigating the calibration sequences)
- `LowlevTauCtrlCalibrator_Proc.m` --> for testing each state processing (training data acquisition, model fitting, each of them for friction or motor parameter `Kpwm`)

### Sanity Tests on the robot
The goal here is only to check the procedure functionality and that we get sound results, since accurate results require fine calibrated FT sensors and joint encoder offsets.

The first tested commit (before any further fix) is the `master` branch commit https://github.com/robotology-playground/sensors-calib-inertial/commit/b0862e08bf452732b1a4a4ece52ac8a880bc63a6.

First tests status on the calibration of the left hip roll joint on the iCub:
- [x] **issue:** Yarpdatadumper PID check failure after launching that same process → https://github.com/robotology-playground/sensors-calib-inertial/issues/10
- [x] overall shape of identified functions seems ok
- [x] **issue** PWM order of magnitude is not as expected. This is due to how the measurements are streamed on the Yarp interface (https://github.com/robotology/icub-main/issues/497). → This has been implemented in https://github.com/robotology-playground/sensors-calib-inertial/pull/12

**Comment by nunoguedelha** [comment]
We depict below the first results from the calibration of the left hip roll joint on the iCub.

#### Joint velocity and friction torque time series
![l_hip_roll-dq2time_and_tau2time](https://user-images.githubusercontent.com/6848872/36087926-2630b57a-0fd5-11e8-954e-af3fdcb7ba65.png)

#### Joint velocity to friction torque function model

![l_hip_roll-dq2tau](https://user-images.githubusercontent.com/6848872/36087983-82c2d1c4-0fd5-11e8-82f5-7dfdcfaf7534.png)

#### PWM and motor torque time series

![l_hip_roll-pwm2time_and_tau2time](https://user-images.githubusercontent.com/6848872/36087990-8f6370a0-0fd5-11e8-8ac7-fb39f31bfe67.png)

#### PWM to motor torque function model

![l_hip_roll-pwm2tau](https://user-images.githubusercontent.com/6848872/36088026-b1381406-0fd5-11e8-8c8b-da1887820cef.png)

**Comment by nunoguedelha** [comment]
FYI @DanielePucci @traversaro @diegoferigo @gabrielenava

**Comment by nunoguedelha** [comment]
@DanielePucci  @traversaro @gabrielenava, here is a friction estimation test (right leg knee) using a realtime plotter for better grasping the static friction around  velocity 0, and Coulomb friction.
![r_knee_frictionest_test1](https://user-images.githubusercontent.com/6848872/38638588-0d16764c-3dcf-11e8-8b01-000591a35502.png)

Estimated values...

Kc ~ 2 Nm
Kv ~ -0.3 Nm/(deg.s-1) ~ 17 Nm/(rad.s-1)

So approximately 30 Nm for 90 deg.s-1 speed, which is reasonable from the feeling we get when pushing the leg.

Mind that this is the friction including the Back Emf (PWM = 0), significantly higher than the friction in Idle mode.

**Comment by nunoguedelha** [comment]
(the fitting above is fake, it is a unit test result. The data plot is real.)

**Comment by nunoguedelha** [comment]
@DanielePucci Joint side.

**Comment by nunoguedelha** [comment]
@DanielePucci @traversaro , as I was discussing with Silvio, the first impression from this figure after all is that:
- the actual Coulomb friction is almost null (if we neglect the data between ± 500 deg/s, we could fit a line spanning the whole range of positive and negative velocities and intersecting the origin)
- around the origin we are actually observing the static friction only (Stribeck curve, example below), which in this case is not negligible as we were expecting (~ 2 Nm)

![stribeck-curve-during-liquid-lubrication](https://user-images.githubusercontent.com/6848872/38668769-ea2cdb96-3e44-11e8-90fe-90b55fa5cf2e.png)

['Stribeck curve during liquid lubrication. ' from publication 'Physicochemistry aspects on frictional interfaces' on ResearchGate]
Note: this would actually explain the first results: https://github.com/robotology-playground/sensors-calib-inertial/issues/9#issuecomment-364853199

Let's wait for the proper fitting results.

**Comment by nunoguedelha** [comment]
@DanielePucci I've edited my [previous comment](https://github.com/robotology-playground/sensors-calib-inertial/issues/9#issuecomment-380571682) as the 2 Nm friction observed around the origin was the **static** friction. Here is the proper fitting performed during the estimation:

We can see below the diagram relating coupling matrix, the gearbox ratios and the measured quantities:

![motortransferfunction](https://user-images.githubusercontent.com/6848872/38741588-84b7b136-3f3a-11e8-9744-e91e57a5d9c9.png)

Where `𝛕_J`(hat) is the joint torque estimated by the WholeBodyDynamics, `ω_m` is the motor shaft angular velocity, and `𝛕_g` and `ω_g` are the same physical quantities that would be measured at the output of the gearbox, before the coupling module.

plot of `𝛕_g` vs `ω_g` from Yarp data dumper log and model `𝛕_g=f(ω_g)` fitting:

![motorvel2torq](https://user-images.githubusercontent.com/6848872/38745104-ea06b90c-3f43-11e8-845f-1d4d12e780e2.png)

### Development and test status.
- The estimation is now running without any glitch for (non-coupled) joints. It takes approximately 10mn for calibrating each joint (friction + PWM). So we should counbt 2h for the full calibration of both legs.
- I don't have results for the torso on the robot yet. I will run the tests on Monday.

**Comment by nunoguedelha** [comment]
The estimation of coupled joints is now fully functional with the following features:
- a PID (Matlab function) controls the motors in PWM mode in order to have 2 over 3 motors blocked position, and 1 with PWM set to 0 (the one being calibrated)
- PID coefficients are hard coded in a local configuration file [`conf/hardwareMechanicalsConfig.m`](https://github.com/robotology-playground/sensors-calib-inertial/blob/fix/missingJointMotorCtrlParameters/src/conf/hardwareMechanicalsConfig.m)
- a new model is used for fitting the parameters: it combines an affine function and an exponential function.


#### Torso motor 2 (roll) friction estimation results

Actually motor 2 and 3 mostly contribute for the pitch DoF.

![torsomotor2frictioncalibpass](https://user-images.githubusercontent.com/6848872/39009790-ea872e84-440c-11e8-8204-be7786f6992a.png)

```
Kc = -0.0014
Kv = -0.1033
Ks+ = -0.1431
Ks- = -1.4548
```

The red fitting curve was obtained while using symmetrical static friction coefficients (forcing `Ks+ = Ks-`). The fitting is incorrect since we get a positive static friction.
The green fitting curve was obtained while using symmetrical static friction coefficients (`Ks+ ≠ Ks-`). The fitting looks much better, and different `Ks+`/`Ks-` are still convenient since it seems that the robot interface admits a `stictionUp` and `stictionDwn` along with the `Kbemf` and `Ktau` parameters.

#### Right leg friction estimation results

**Comment by nunoguedelha** [comment]
Tests completed. Closing issue.

**Comment by nunoguedelha** [comment]
@DanielePucci

**Comment by nunoguedelha** [comment]
Cc @traversaro

**Comment by nunoguedelha** [comment]
CC @vibhoraggarwal

**Comment by lrapetti** [comment]
@nunoguedelha where can I find the most recent estimated parameters?

**Comment by vibhoraggarwal** [comment]
@lrapetti  https://github.com/loc2/component_wholebody-teleoperation/issues/7#issuecomment-389804867 has some values that @nunoguedelha estimated.

**Comment by nunoguedelha** [comment]
@lrapetti ,those mentioned by @vibhoraggarwal are for the legs. For the torso, there is https://github.com/loc2/component_wholebody-teleoperation/issues/9. But none of the arm joints were estimated.

**Comment by lrapetti** [comment]
> But none of the arm joints were estimated

@nunoguedelha
How is the torque control for the arms implemented then?

**Comment by nunoguedelha** [comment]
@lrapetti as far as I know, the parameters have been estimated manually by trial and error, not through a model fitting process.

**Comment by lrapetti** [comment]
@nunoguedelha 
I was comparing the data from https://github.com/loc2/component_wholebody-teleoperation/issues/7#issue-281293487 and https://github.com/loc2/component_wholebody-teleoperation/issues/9 with those in the [_robots-configuration_](https://github.com/loc2/robots-configuration/commit/2e3a952addc9faf6e069eb66e380730f550fe749), but I can't see the relationship between $K_v$ and the `trq_kbemf`.
What I see from the model is that:
- $\text{trq_ktau} = \frac{1}{K_{pwm}}$ (this is verified from data)
- $\text{trq_kbemf} = - \frac{K_v}{K_{pwm}}$ (this seems not to be true)

Is there something I am missing?
The measuring units seem to be all in `deg/s`, `Nm` and `dutycycle% [-100/100]`. So no conversion problem should be involved.

**Comment by nunoguedelha** [comment]
@lrapetti , as I told you F2F, there is a conversion between the values estimated here and the `trq_kbemf`, due to the difference in the definitions here and in the low level torque control code, shown below (we can drop the Coulomb friction for simplifying):
- Joint torque model used here: the $K_v$ is an algebraic negative parameter, since $K_v \\, \omega$ is a friction term.
$$
\tau_J = K_{pwm} \\, \mathbf{PWM} + K_v \\, \omega_g
$$
Where $\omega_g$ is the output angular velocity of the gearbox. Typically, for joints without coupling, $\omega_g = \dot{q}$, the joint velocity.
- Low level torque control code: $K_{bemf}$ is a factor defined as an absolute value.
$$
\tau_J = K_{pwm} \\, \mathbf{PWM} - K_{bemf} \\, \omega_m
\leftrightarrow \mathbf{PWM} = K_{\tau} \( \tau_J + K_{bemf} \\, \omega_m \)
$$ 
Where $K_{\tau} = K_{pwm}^{-1}$, and $\omega_m$ is the output angular velocity of the motor shaft, directly measured by the motor encoders, as illustrated in [this comment](https://github.com/robotology-playground/sensors-calib-inertial/issues/9#issuecomment-381196020) from this same issue.

As $\omega_m = G \\, \omega_g$, where $G$ is the gearbox ratio, we get the following relation between $K_{bemf}$ and $K_v$:
$$
- K_{bemf} \\, G \\, \omega_g = K_v \\, \omega_g
\leftrightarrow K_{bemf} = - K_v \\, G^{-1}
$$

**Comment by lrapetti** [comment]
> @lrapetti , as I told you F2F, there is a conversion between the values estimated here and the `trq_kbemf`, due to the difference in the definitions here and in the low level torque control code, shown below (we can drop the Coulomb friction for simplifying):
>  * Joint torque model used here: the KvK_v is an algebraic negative parameter, since KvωK_v \, \omega is a friction term.
> $$ \tau_J = K_{pwm} \, \mathbf{PWM} + K_v \, \omega_g  $$

@nunoguedelha 
According to the variables name given in the scheme [above](https://user-images.githubusercontent.com/6848872/38741588-84b7b136-3f3a-11e8-9744-e91e57a5d9c9.png), I think $ \tau_J $ corresponds to $\tau_g$ (before the coupling). Otherwise it couldn't be related to a single motor PWM in case of coupled joints.
